#!/usr/bin/env bash

#./setlabels-and-milestones.sh PenCue/timber_azure
#./setlabels-and-milestones.sh PenCue/timber_core
#./setlabels-and-milestones.sh PenCue/timber_test
#./setlabels-and-milestones.sh PenCue/timber_schema
#./setlabels-and-milestones.sh PenCue/timber_docs
./setlabels-and-milestones.sh PenCue/bucksaw
./setlabels-and-milestones.sh PenCue/chainsaw
./setlabels-and-milestones.sh PenCue/timber_admin_object
./setlabels-and-milestones.sh PenCue/timber_admin_timeline
./setlabels-and-milestones.sh PenCue/timber_admin_trinity
./setlabels-and-milestones.sh PenCue/timber_calc_pac
./setlabels-and-milestones.sh PenCue/timber_frontend_api
./setlabels-and-milestones.sh PenCue/timber_infra
./setlabels-and-milestones.sh PenCue/timber_lib
./setlabels-and-milestones.sh PenCue/timber_mother
./setlabels-and-milestones.sh PenCue/timber_release
./setlabels-and-milestones.sh PenCue/timber_search_indexer
./setlabels-and-milestones.sh PenCue/timber_test
./setlabels-and-milestones.sh PenCue/timber_analytics_factory
